spring.application.name=Forza

spring.datasource.url=jdbc:postgresql://localhost/forza
spring.datasource.username=postgres
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${DB_EMA}
spring.mail.password=${DB_MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


api.security.token.secret=${TK_SECRET}

spring.security.oauth2.client.registration.google.client-secret=${CLI_SECRET}
spring.security.oauth2.client.registration.google.client-id=${CLI_ID}

spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


spring.security.oauth2.client.registration.github.client-id=${GIT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GIT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email